add mysql_compatibility doc in Chinese
secretflow/scql pull request #74
Opened 2023-06-11 03:21 UTC by winterpi

[将 SCQL《MySQL Compatibility》英文文档逐句翻译成中文文档#70](https://github.com/secretflow/scql/issues/70)

2023-06-12 01:20 UTC, winterpi commented
I have read the CLA Document and I hereby sign the CLA

2023-06-12 01:58 UTC, 6fj commented
Closes #70

2023-06-12 05:52 UTC, tongke6 requested changes

2023-06-12 05:52 UTC, tongke6 commented on docs/locales/zh_CN/LC_MESSAGES/reference/mysql_compatibility.po
> +msgstr "创建表格"
表格 --> `表` or `数据表`

2023-06-12 05:52 UTC, tongke6 commented on docs/locales/zh_CN/LC_MESSAGES/reference/mysql_compatibility.po
> +msgstr "SCQL 从 GRM 获取表格模式，所以 CREATE TABLE 的语句必须包含关键字 TID，该关键字在 GRM 中标识一个唯一的表格。有关更多信息，请阅读：doc:`scql_manual`。"
table schema 翻译成 `表规格` 更好一点

参考

比较赞同这里的翻译：https://m.mysmth.net/article/Programming/188564?au=Dieken

2023-06-12 06:25 UTC, tyrone-yu commented on docs/locales/zh_CN/LC_MESSAGES/reference/mysql_compatibility.po
> +msgstr "与 MySQL 的兼容性"
作为标题的话，直接翻译为“MySQL 兼容性”或者“MySQL 兼容性文档”可能会好一点

2023-06-12 06:25 UTC, tyrone-yu commented on docs/locales/zh_CN/LC_MESSAGES/reference/mysql_compatibility.po
> +msgstr "与 MySQL 不同的功能"
与 MySQL 不同的功能 -> 与 MySQL 存在语法差异的功能

2023-06-12 06:25 UTC, tyrone-yu commented on docs/locales/zh_CN/LC_MESSAGES/reference/mysql_compatibility.po
> +msgstr "返回整型"
建议数据类型不要翻译，或者在翻译后的中文带上英文的数据类型

2023-06-12 06:25 UTC, tyrone-yu commented on docs/locales/zh_CN/LC_MESSAGES/reference/mysql_compatibility.po
> +msgstr "单方的查询"
单方的查询 -> 单方查询

2023-06-12 06:25 UTC, tyrone-yu commented on docs/locales/zh_CN/LC_MESSAGES/reference/mysql_compatibility.po
> +msgstr "如果两个参数都是长整型，则使用长整型的方式比较。"
这里建议不要将 long 翻译为长整型，SCQL 内部 long 型的长度就是 int 型，翻译成中文可能会引起误解，建议仍使用英文的 long 描述

2023-06-13 01:51 UTC, winterpi commented on docs/locales/zh_CN/LC_MESSAGES/reference/mysql_compatibility.po
> +msgstr "SCQL 从 GRM 获取表格模式，所以 CREATE TABLE 的语句必须包含关键字 TID，该关键字在 GRM 中标识一个唯一的表格。有关更多信息，请阅读：doc:`scql_manual`。"
OK

2023-06-13 01:51 UTC, winterpi commented on docs/locales/zh_CN/LC_MESSAGES/reference/mysql_compatibility.po
> +msgstr "返回整型"
changed

2023-06-13 01:51 UTC, winterpi commented on docs/locales/zh_CN/LC_MESSAGES/reference/mysql_compatibility.po
> +msgstr "单方的查询"
OK

2023-06-13 01:52 UTC, winterpi commented on docs/locales/zh_CN/LC_MESSAGES/reference/mysql_compatibility.po
> +msgstr "如果两个参数都是长整型，则使用长整型的方式比较。"
已修改

2023-06-13 01:52 UTC, winterpi commented on docs/locales/zh_CN/LC_MESSAGES/reference/mysql_compatibility.po
> +msgstr "与 MySQL 不同的功能"
已修改

2023-06-13 07:21 UTC, winterpi commented on docs/locales/zh_CN/LC_MESSAGES/reference/mysql_compatibility.po
> +msgstr "创建表格"
OK

2023-06-13 07:25 UTC, tongke6 approved these changes
LGTM

2023-06-13 07:25 UTC, merged