[docs] add Deployment doc in chinese
secretflow/scql pull request #77
Opened 2023-06-15 02:36 UTC by kpretty

#65

2023-06-15 02:36 UTC, kpretty commented
I have read the CLA Document and I hereby sign the CLA

2023-06-19 04:03 UTC, taochen-ant requested changes

2023-06-19 04:03 UTC, taochen-ant commented on docs/locales/zh_CN/LC_MESSAGES/getting_started/deployment.po
> +msgstr "``conn_str`` 用于连接 scdb 的数据库，该数据库将在下一步中部署，"
``conn_str`` 用于连接一个名为SCDB的数据库，该数据库将在2.4 节中通过docker-compose完成部署。你可以根据自己的需求来设置对应的数据库连接串（ps:这里的英文描述的不是很清晰，可以自己发挥一下。不需要逐句翻译。）

2023-06-19 04:03 UTC, taochen-ant commented on docs/locales/zh_CN/LC_MESSAGES/getting_started/deployment.po
> +msgstr "``__SCDB_PORT__`` 用于监听 scdb 服务的发布端口，您需要用一个可访问的端口号替换它。"
"``__SCDB_PORT__`` 是SCDB服务在宿主机上的监听端口。

2023-06-19 04:20 UTC, kpretty commented
@taochen-ant fixed

2023-06-19 10:39 UTC, taochen-ant commented on docs/locales/zh_CN/LC_MESSAGES/getting_started/deployment.po
> +"包括一个可信的第三方和两个名为 ``Alice`` 和 ``Bob`` 的数据所有方。"
数据所有方 -> 数据提供方 or 数据拥有方

2023-06-19 10:47 UTC, kpretty commented
@taochen-ant fixed

2023-06-19 14:00 UTC, tongke6 commented on docs/locales/zh_CN/LC_MESSAGES/getting_started/deployment.po
> +msgstr "引擎中的数据库用于存储原始数据。在本文档中我们将使用 MYSQL 作为数据库服务并模拟一个数据集，"
MYSQL --》 MySQL

2023-06-20 01:03 UTC, kpretty commented
@tongke6 fixed

2023-06-20 02:39 UTC, tongke6 approved these changes
LGTM

2023-06-20 02:55 UTC, taochen-ant approved these changes

2023-06-20 02:55 UTC, merged