[docs] add scql_status doc in chinese
secretflow/scql pull request #78
Opened 2023-06-16 08:05 UTC by addingIce

[docs] add scql_status doc in chinese

2023-06-16 08:38 UTC, addingIce commented
I have read the CLA Document and I hereby sign the CLA

2023-06-18 12:05 UTC, Mingbo-Lee requested changes

2023-06-18 12:05 UTC, Mingbo-Lee commented on docs/locales/zh_CN/LC_MESSAGES/reference/scql_status.po
> +msgstr "where clause"
clause -> 子句

2023-06-18 12:05 UTC, Mingbo-Lee commented on docs/locales/zh_CN/LC_MESSAGES/reference/scql_status.po
> +msgstr "group by clause"
clause -> 子句

2023-06-18 12:05 UTC, Mingbo-Lee commented on docs/locales/zh_CN/LC_MESSAGES/reference/scql_status.po
> +msgstr "having clause"
clause -> 子句

2023-06-18 12:05 UTC, Mingbo-Lee commented on docs/locales/zh_CN/LC_MESSAGES/reference/scql_status.po
> +msgstr "limit clause"
clause -> 子句

2023-06-18 12:05 UTC, Mingbo-Lee commented on docs/locales/zh_CN/LC_MESSAGES/reference/scql_status.po
> +msgstr "order by clause"
clause -> 子句

2023-06-19 02:22 UTC, addingIce commented on docs/locales/zh_CN/LC_MESSAGES/reference/scql_status.po
> +msgstr "where clause"
已修改

2023-06-19 02:22 UTC, addingIce commented on docs/locales/zh_CN/LC_MESSAGES/reference/scql_status.po
> +msgstr "group by clause"
已修改

2023-06-19 02:22 UTC, addingIce commented on docs/locales/zh_CN/LC_MESSAGES/reference/scql_status.po
> +msgstr "having clause"
已修改

2023-06-19 02:22 UTC, addingIce commented on docs/locales/zh_CN/LC_MESSAGES/reference/scql_status.po
> +msgstr "limit clause"
已修改

2023-06-19 02:22 UTC, addingIce commented on docs/locales/zh_CN/LC_MESSAGES/reference/scql_status.po
> +msgstr "order by clause"
已修改

2023-06-19 10:05 UTC, Mingbo-Lee requested changes

2023-06-19 10:05 UTC, Mingbo-Lee commented on docs/locales/zh_CN/LC_MESSAGES/reference/scql_status.po
> +msgstr "不支持字符串类型比较"
字符串类型 -> 字符串类型数据

2023-06-19 11:15 UTC, Mingbo-Lee approved these changes

2023-06-19 11:16 UTC, Mingbo-Lee commented
LGTM

2023-06-19 13:24 UTC, tongke6 commented on docs/locales/zh_CN/LC_MESSAGES/reference/scql_status.po
> +msgstr "关键字 ``using`` 暂不支持"
中文一般不用倒装语法，建议修改成：暂不支持关键字 \``using\``

2023-06-20 01:24 UTC, addingIce commented on docs/locales/zh_CN/LC_MESSAGES/reference/scql_status.po
> +msgstr "关键字 ``using`` 暂不支持"
已修改

2023-06-20 01:27 UTC, tongke6 approved these changes
LGTM

2023-06-20 01:27 UTC, merged