Updated quickstart.po
secretflow/scql pull request #82
Opened 2023-06-18 08:57 UTC by Matty-7

2023-06-18 11:30 UTC, Mingbo-Lee commented
resolve https://github.com/secretflow/scql/issues/63

2023-06-18 12:06 UTC, Mingbo-Lee requested changes

2023-06-18 12:10 UTC, Mingbo-Lee requested changes

2023-06-18 12:10 UTC, Mingbo-Lee commented on docs/locales/zh_CN/LC_MESSAGES/getting_started/quickstart.po
你 -> 您

2023-06-18 12:11 UTC, Mingbo-Lee commented
ref to
![image](https://github.com/secretflow/scql/assets/51162830/5a333914-b09c-45f4-a6c6-f5dcea7fa5c8)
update your title.

2023-06-19 01:17 UTC, tongke6 commented on docs/locales/zh_CN/LC_MESSAGES/getting_started/quickstart.po
> +msgstr "建立 scdbclient"
build 翻译成 `构建` 更合适点

2023-06-19 01:17 UTC, tongke6 commented on docs/locales/zh_CN/LC_MESSAGES/getting_started/quickstart.po
> +msgstr "在启动 SCQL 服务之前，您需要在 ToyGRM 中初始化令牌和凭证，并将这些信息放入 user.json 和引擎的配置文件中。"
放入 --> 写入？

2023-06-19 01:17 UTC, tongke6 commented on docs/locales/zh_CN/LC_MESSAGES/getting_started/quickstart.po
> +msgstr "启动SCQL服务"
请在 `SCQL` 前后加空格

ref: 中英文混排时中间加空格

2023-06-19 01:17 UTC, tongke6 commented on docs/locales/zh_CN/LC_MESSAGES/getting_started/quickstart.po
> +msgstr "你可以通过 `docker-compose <https://github.com/secretflow/scql/tree/main/examples/docker-compose>`_ 来启动 SCQL 服务 ，它将部署和启动服务，如下图所示，它包含一个 SCDBServer 和两个来自 ``alice`` 方、 ``bob`` 的 SCQLEngines 。"
> 和两个来自 ``alice`` 方、 ``bob`` 的 SCQLEngines

建议修改成： 和两个分别来自参与方 ``alice``、``bob`` 的 SCQLEngines

2023-06-19 01:17 UTC, tongke6 commented on docs/locales/zh_CN/LC_MESSAGES/getting_started/quickstart.po
> +msgstr "SCDBServer 是通过 HTTP 协议提供的。然而，对于生产环境，建议使用 HTTPS 来代替。请查看 :ref:`TLS 配置 <scdb-tls>` 以了解详情。"
> 是通过 HTTP 协议提供的

建议修改成 -> 是通过 HTTP 协议提供服务的

> 建议使用 HTTPS 来替代

建议修改成 -> 建议使用 HTTPS 协议

2023-06-19 01:17 UTC, tongke6 commented on docs/locales/zh_CN/LC_MESSAGES/getting_started/quickstart.po
> +msgstr "创建数据库、用户和表格"
表格 --> 表 or 数据表

2023-06-19 01:47 UTC, tongke6 approved these changes
nice work~

LGTM

2023-06-19 01:47 UTC, merged