[docs]  add integrate scql system in chinese
secretflow/scql pull request #84
Opened 2023-06-18 16:04 UTC by hacker-jerry

#72

2023-06-19 08:58 UTC, Mingbo-Lee approved these changes
ref to 
![image](https://github.com/secretflow/scql/assets/51162830/9d5194e3-729f-45aa-9fdc-88d6e5ba28fc)
update your title.

2023-06-19 10:14 UTC, Mingbo-Lee requested changes

2023-06-19 10:14 UTC, Mingbo-Lee commented on docs/locales/zh_CN/LC_MESSAGES/development/integrate_scql_system.po
> +msgstr "如图所示，SCQL 系统需要与**客户端**和**全局资源管理器**配合工作："
客户端->客户端（Client）
全局资源管理器->全局资源管理器（GRM）

2023-06-19 10:14 UTC, Mingbo-Lee commented on docs/locales/zh_CN/LC_MESSAGES/development/integrate_scql_system.po
> -msgstr ""
客户端->客户端（Client）

2023-06-19 10:14 UTC, Mingbo-Lee commented on docs/locales/zh_CN/LC_MESSAGES/development/integrate_scql_system.po
`interface` should translated to `接口`

2023-06-19 10:14 UTC, Mingbo-Lee commented on docs/locales/zh_CN/LC_MESSAGES/development/integrate_scql_system.po
> +msgstr "全局资源管理器：有助于管理模式信息和识别各方。"
全局资源管理器->全局资源管理器（GRM）

2023-06-19 10:14 UTC, Mingbo-Lee commented on docs/locales/zh_CN/LC_MESSAGES/development/integrate_scql_system.po
> +msgstr "因此，平台应该支持客户端和全局资源管理器来集成 SCQL 系统。"
all  should be 
```
客户端->客户端（Client）
全局资源管理器->全局资源管理器（GRM）
```

2023-06-20 02:20 UTC, jingshi-ant commented on docs/locales/zh_CN/LC_MESSAGES/development/integrate_scql_system.po
> +msgstr "客户端（Client）：被设计成用于查询提交和结果检索的用户接口。"
suggestion：为提交查询、获取结果而设计的用户接口

2023-06-20 02:20 UTC, jingshi-ant commented on docs/locales/zh_CN/LC_MESSAGES/development/integrate_scql_system.po
> +msgstr "因此，平台应该支持客户端（Client）和全局资源管理器（GRM）来集成 SCQL 系统。"
支持 -> 提供

2023-06-20 02:20 UTC, jingshi-ant commented on docs/locales/zh_CN/LC_MESSAGES/development/integrate_scql_system.po
> +msgstr "Submit：异步 API，只需提交 SQL 查询并返回，服务器监听``${SCDBHost}/public/submit_query``"
只需 -> 用于

2023-06-20 02:20 UTC, jingshi-ant commented on docs/locales/zh_CN/LC_MESSAGES/development/integrate_scql_system.po
> +msgstr "全局资源管理器（GRM）：有助于管理模式信息和识别各方。"
负责管理表规格信息、校验参与方身份

2023-06-20 05:03 UTC, tongke6 commented on docs/locales/zh_CN/LC_MESSAGES/development/integrate_scql_system.po
> +msgstr "如图所示，SCQL 系统需要与**客户端（Client）**和**全局资源管理器（GRM）**配合工作："
请添加相应的空格，比如：

> SCQL 系统需要与 \*\*客户端（Client）\*\* 和 \*\*全局资源管理器（GRM）\*\* 配合工作

2023-06-20 05:03 UTC, tongke6 commented on docs/locales/zh_CN/LC_MESSAGES/development/integrate_scql_system.po
> +msgstr "请阅读:doc:`../reference/grm`了解更多关于 GRM 的信息。"
请在阅读后面添加空格

2023-06-20 05:03 UTC, tongke6 commented on docs/locales/zh_CN/LC_MESSAGES/development/integrate_scql_system.po
> +msgstr "自定义的全局资源管理器服务器（Custom GRM server）需要支持上述与GRM API 对应的服务。"
中英文混排请注意添加空格

2023-06-20 05:10 UTC, tongke6 approved these changes

2023-06-20 05:10 UTC, tongke6 commented
LGTM

2023-06-20 05:11 UTC, merged