[docs] add manual doc in Chinese
secretflow/scql pull request #96
Opened 2023-06-30 08:21 UTC by awusan125

resolve https://github.com/secretflow/scql/issues/66

2023-06-30 08:22 UTC, awusan125 commented
I have read the CLA Document and I hereby sign the CLA

2023-06-30 08:24 UTC, awusan125 commented
I have read the CLA Document and I hereby sign the CLA

2023-06-30 12:34 UTC, Mingbo-Lee requested changes

2023-06-30 12:34 UTC, Mingbo-Lee commented on docs/locales/zh_CN/LC_MESSAGES/reference/scql_manual.po
> +msgstr "例子："
例子 - > 样例

2023-06-30 12:34 UTC, Mingbo-Lee commented on docs/locales/zh_CN/LC_MESSAGES/reference/scql_manual.po
> +"该物理表由 'TID' 指定且位于相关方上。在 SCQL 中，"
相关方 -> 相关参与方

2023-06-30 12:34 UTC, Mingbo-Lee commented on docs/locales/zh_CN/LC_MESSAGES/reference/scql_manual.po
> +"控制和使用。"
特权 -> 权限

2023-06-30 12:34 UTC, Mingbo-Lee commented on docs/locales/zh_CN/LC_MESSAGES/reference/scql_manual.po
稍后 -> 之后

2023-06-30 12:50 UTC, Mingbo-Lee approved these changes
LGTM

2023-07-05 01:42 UTC, tongke6 commented on docs/locales/zh_CN/LC_MESSAGES/reference/scql_manual.po
> +"SCQL 兼容大多数MySQL语法，这使得它易于使用。"
MySQL 前后请添加相应的空格

2023-07-07 02:58 UTC, tongke6 approved these changes
LGTM

2023-07-07 02:59 UTC, merged